title: Demoing Jekyll with Github Pages
author: Kunal Patel
email: patelkunal89@gmail.com
description: >- # this means to ignore newlines until 
  A simple/minimal Jekyll site configured by Copilot and hosted on GitHub Pages.
baseurl: "/jekyll-demo-01" # the subpath of your site, e.g. /jekyll-demo-01
url: "https://patelkunal.github.io" # the base hostname & protocol for your site

# Build settings
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
