title: Jekyll Demo 01
email: your-email@example.com
description: >- # this means to ignore newlines until 
  A simple Jekyll site configured by Copilot.
baseurl: "/jekyll-demo-01" # the subpath of your site, e.g. /jekyll-demo-01
url: "https://patelkunal.github.io" # the base hostname & protocol for your site

# Build settings
theme: minima
plugins:
  - jekyll-feed
